    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
                <div class="panel-heading">
                    <a id="logo" href="<?php echo BASE; ?>">
                        <img class="img-responsive" src="<?php echo IMG; ?>Levrochet-Logo.png" alt="">
                    </a>
                    <?php echo (isset($this->menu) ? $this->menu : ''); ?>
                </div>
                <div class="panel-body">
                    <?php echo (isset($this->alert) ? $this->alert : ''); ?>
                    <form action="<?php echo BASE; ?>recuperar/solicitar/" class="form-horizontal" method="post">
                      <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">E-mail:</label>
                        <div class="col-sm-8">
                          <input required type="email" name="email" class="form-control" id="email" placeholder="seuemail@dominio.com.br" value="<?php echo $this->request->post('email') ?>">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                        <a href="<?php echo BASE; ?>login/" style="color:#ffffff;">Voltar ao Login</a><br>
                          <button type="submit" class="btn btn-success">Enviar Link de redefinição</button>
                        </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
